// Partners data
export const partners = {
  developer: [
    {
      id: 1,
      name: 'Masterise Homes',
      shortDescription: 'Chủ đầu tư cao cấp',
      description:
        'Chuyên phát triển bất động sản hạng sang tại các khu vực trung tâm TP.HCM.',
      logoUrl: '/developer-partner/masterise-homes.png',
      projectCount: 5,
      partnershipYear: '2020',
      revenue: '49.7 triệu USD',
      specialties: ['Luxury', 'Mixed-use', 'Residential'],
      achievements: [
        'Premium Partner',
        'Luxury Specialist',
        'Innovation Award',
      ],
    },
    {
      id: 2,
      name: 'Ecopark',
      shortDescription: 'Chủ đầu tư xanh',
      description:
        'Tập trung vào các dự án bất động sản xanh, thân thiện với môi trường.',
      logoUrl: '/developer-partner/ecopark.png',
      projectCount: 2,
      partnershipYear: '2018',
      revenue: '54.9 triệu USD',
      specialties: ['Eco-living', 'Township', 'Residential'],
      achievements: ['Green Developer', 'Sustainable Design'],
    },
    {
      id: 3,
      name: 'Gamuda Land',
      shortDescription: 'Chủ đầu tư quốc tế',
      description:
        'Nhà phát triển bất động sản quốc tế với các dự án quy mô lớn.',
      logoUrl: '/developer-partner/gamuda-land.png',
      projectCount: 2,
      partnershipYear: '2019',
      revenue: '77.8 triệu USD',
      specialties: ['Township', 'Residential', 'Park-integrated'],
      achievements: ['International Developer', 'Master Plan Excellence'],
    },
    {
      id: 4,
      name: 'CapitaLand',
      shortDescription: 'Chủ đầu tư quốc tế',
      description:
        'Tập đoàn bất động sản hàng đầu châu Á với các dự án cao cấp.',
      logoUrl: '/developer-partner/capitaland.png',
      projectCount: 2,
      partnershipYear: '2017',
      revenue: '10.2 triệu USD',
      specialties: ['Luxury', 'Condo', 'Urban living'],
      achievements: ['Asia Developer', 'Quality Excellence'],
    },
    {
      id: 5,
      name: 'Phú Mỹ Hưng',
      shortDescription: 'Chủ đầu tư đô thị',
      description: 'Phát triển các khu đô thị hiện đại tại TP.HCM.',
      logoUrl: '/developer-partner/phu-my-hung.png',
      projectCount: 1,
      partnershipYear: '2015',
      revenue: '31.0 triệu USD',
      specialties: ['Urban residential', 'Mixed-use'],
      achievements: ['Urban Developer', 'Community Excellence'],
    },
    {
      id: 6,
      name: 'Keppel Land',
      shortDescription: 'Chủ đầu tư quốc tế',
      description:
        'Nhà phát triển bất động sản đến từ Singapore với các dự án cao cấp.',
      logoUrl: '/developer-partner/keppel-land.png',
      projectCount: 3,
      partnershipYear: '2016',
      revenue: '35.2 triệu USD',
      specialties: ['Luxury', 'Mixed-use', 'High-rise residential'],
      achievements: ['Premium Developer', 'Innovation Award'],
    },
    {
      id: 7,
      name: 'VinHomes',
      shortDescription: 'Chủ đầu tư hàng đầu',
      description:
        'Nhà phát triển bất động sản lớn nhất Việt Nam với các dự án quy mô.',
      logoUrl: '/developer-partner/vinhomes.webp',
      projectCount: 0,
      partnershipYear: '2018',
      revenue: '0',
      specialties: ['Residential', 'Urban areas', 'Commercial'],
      achievements: ['Market Leader', 'Scale Excellence'],
    },
    {
      id: 8,
      name: 'Novaland',
      shortDescription: 'Chủ đầu tư đa ngành',
      description:
        'Phát triển các dự án bất động sản đa dạng từ nhà ở đến nghỉ dưỡng.',
      logoUrl: '/developer-partner/novaland.png',
      projectCount: 2,
      partnershipYear: '2017',
      revenue: '51.5 triệu USD',
      specialties: ['Township', 'Resort', 'Residential'],
      achievements: ['Versatile Developer', 'Market Expansion'],
    },
    {
      id: 9,
      name: 'BCG Land',
      shortDescription: 'Chủ đầu tư đa năng',
      description:
        'Phát triển các dự án bất động sản đa dạng tại nhiều khu vực.',
      logoUrl: '/developer-partner/bcg-land.png',
      projectCount: 3,
      partnershipYear: '2019',
      revenue: '54.7 triệu USD',
      specialties: ['Luxury', 'Resort', 'Villa'],
      achievements: ['Dynamic Developer', 'Regional Expansion'],
    },

    {
      id: 10,
      name: 'SwanCity (Tập đoàn CFLD)',
      shortDescription: 'Chủ đầu tư quốc tế',
      description: 'Phát triển các dự án bất động sản quy mô lớn tại Việt Nam.',
      logoUrl: '/developer-partner/cfld.png',
      projectCount: 1,
      partnershipYear: '2020',
      revenue: '83.5 triệu USD',
      specialties: ['Urban development', 'Township'],
      achievements: ['International Developer', 'Large-scale Projects'],
    },
    {
      id: 11,
      name: 'SonKim Land',
      shortDescription: 'Chủ đầu tư cao cấp',
      description: 'Chuyên về các dự án bất động sản hạng sang và hiện đại.',
      logoUrl: '/developer-partner/son-kim-land.avif',
      projectCount: 2,
      partnershipYear: '2018',
      revenue: '32.3 triệu USD',
      specialties: ['Luxury apartments', 'Mixed-use'],
      achievements: ['Luxury Developer', 'Design Excellence'],
    },
    {
      id: 12,
      name: 'Khang Điền',
      shortDescription: 'Chủ đầu tư nhà ở',
      description: 'Tập trung phát triển các dự án nhà ở chất lượng cao.',
      logoUrl: '/developer-partner/khang-dien.png',
      projectCount: 2,
      partnershipYear: '2016',
      revenue: '16.3 triệu USD',
      specialties: ['Residential', 'Townhouses'],
      achievements: ['Residential Specialist', 'Quality Award'],
    },
    {
      id: 13,
      name: 'Điền Phúc Thành',
      shortDescription: 'Chủ đầu tư đa dạng',
      description: 'Phát triển các dự án căn hộ và nhà ở tại TP.HCM.',
      logoUrl: '/developer-partner/dien-phuc-thanh.png',
      projectCount: 2,
      partnershipYear: '2019',
      revenue: '30.4 triệu USD',
      specialties: ['Apartments', 'Riverside living'],
      achievements: ['Regional Developer', 'Market Growth'],
    },
    {
      id: 14,
      name: 'IFF Holdings',
      shortDescription: 'Chủ đầu tư nghỉ dưỡng',
      description:
        'Chuyên phát triển các dự án bất động sản nghỉ dưỡng cao cấp.',
      logoUrl: '/developer-partner/iff-holdings.png',
      projectCount: 1,
      partnershipYear: '2021',
      revenue: '22.2 triệu USD',
      specialties: ['Resort', 'Hospitality'],
      achievements: ['Resort Developer', 'Luxury Hospitality'],
    },
    {
      id: 15,
      name: 'Lodgis Hospitality',
      shortDescription: 'Chủ đầu tư nghỉ dưỡng',
      description: 'Phát triển các dự án bất động sản nghỉ dưỡng và khách sạn.',
      logoUrl: '/developer-partner/lodgis-hospitality.png',
      projectCount: 1,
      partnershipYear: '2020',
      revenue: '22.0 triệu USD',
      specialties: ['Resort', 'Hospitality'],
      achievements: ['Hospitality Developer', 'Service Excellence'],
    },
    {
      id: 16,
      name: 'Madison Land',
      shortDescription: 'Chủ đầu tư nghỉ dưỡng',
      description:
        'Tập trung vào các dự án bất động sản nghỉ dưỡng tại khu vực ven biển.',
      logoUrl: '/developer-partner/madison-land.png',
      projectCount: 1,
      partnershipYear: '2021',
      revenue: '16.5 triệu USD',
      specialties: ['Resort', 'Luxury villas'],
      achievements: ['Coastal Developer', 'Luxury Resort'],
    },
    {
      id: 17,
      name: 'Frasers Property',
      shortDescription: 'Chủ đầu tư quốc tế',
      description: 'Nhà phát triển bất động sản quốc tế với các dự án cao cấp.',
      logoUrl: '/developer-partner/frasers-project.png',
      projectCount: 1,
      partnershipYear: '2018',
      revenue: '12.4 triệu USD',
      specialties: ['Luxury condo', 'Residential'],
      achievements: ['International Developer', 'Quality Design'],
    },
    {
      id: 18,
      name: 'Tây Hồ Group',
      shortDescription: 'Chủ đầu tư đô thị',
      description: 'Phát triển các khu đô thị và dự án nhà ở hiện đại.',
      logoUrl: '/developer-partner/tay-ho-group.png',
      projectCount: 1,
      partnershipYear: '2019',
      revenue: '12.1 triệu USD',
      specialties: ['Urban development', 'Residential'],
      achievements: ['Urban Developer', 'Community Growth'],
    },

    {
      id: 19,
      name: 'Hongkong Land',
      shortDescription: 'Chủ đầu tư quốc tế',
      description: 'Tập đoàn bất động sản quốc tế với các dự án hạng sang.',
      logoUrl: '/developer-partner/hongkong-land.png',
      projectCount: 1,
      partnershipYear: '2017',
      revenue: '9.6 triệu USD',
      specialties: ['Luxury apartments', 'High-end residential'],
      achievements: ['Premium Developer', 'Luxury Excellence'],
    },
    {
      id: 20,
      name: 'Mapletree',
      shortDescription: 'Chủ đầu tư quốc tế',
      description:
        'Nhà phát triển bất động sản đến từ Singapore với các dự án chất lượng.',
      logoUrl: '/developer-partner/mapletree.png',
      projectCount: 1,
      partnershipYear: '2018',
      revenue: '9.0 triệu USD',
      specialties: ['Condo', 'Riverside residential'],
      achievements: ['International Developer', 'Quality Projects'],
    },
    {
      id: 21,
      name: 'Nam Long',
      shortDescription: 'Chủ đầu tư nhà ở',
      description: 'Chuyên phát triển các dự án nhà ở giá trị thực.',
      logoUrl: '/developer-partner/nam-long.webp',
      projectCount: 1,
      partnershipYear: '2016',
      revenue: '7.2 triệu USD',
      specialties: ['Affordable housing', 'Urban residential'],
      achievements: ['Residential Developer', 'Market Reach'],
    },
    {
      id: 22,
      name: 'Trung Thủy Group',
      shortDescription: 'Chủ đầu tư cao cấp',
      description: 'Phát triển các dự án bất động sản hạng sang và sáng tạo.',
      logoUrl: '/developer-partner/trung-thuy-group.png',
      projectCount: 1,
      partnershipYear: '2019',
      revenue: '7.2 triệu USD',
      specialties: ['Luxury apartments', 'Downtown projects'],
      achievements: ['Innovative Developer', 'Design Award'],
    },
    {
      id: 23,
      name: 'Sunwah Group',
      shortDescription: 'Chủ đầu tư quốc tế',
      description:
        'Tập đoàn quốc tế phát triển bất động sản cao cấp tại Việt Nam.',
      logoUrl: '/developer-partner/sunwah-group.png',
      projectCount: 1,
      partnershipYear: '2018',
      revenue: '7.3 triệu USD',
      specialties: ['Luxury apartments', 'Riverside towers'],
      achievements: ['International Developer', 'Market Presence'],
    },
    {
      id: 24,
      name: 'Sapphire',
      shortDescription: 'Chủ đầu tư nghỉ dưỡng',
      description:
        'Chuyên phát triển các dự án bất động sản nghỉ dưỡng ven biển.',
      logoUrl: '/developer-partner/sapphire.png',
      projectCount: 1,
      partnershipYear: '2020',
      revenue: '6.9 triệu USD',
      specialties: ['Resort', 'Beachfront villas'],
      achievements: ['Resort Developer', 'Coastal Excellence'],
    },
    {
      id: 25,
      name: 'Charm Group',
      shortDescription: 'Chủ đầu tư nghỉ dưỡng',
      description: 'Phát triển các dự án bất động sản nghỉ dưỡng cao cấp.',
      logoUrl: '/developer-partner/charm-group.png',
      projectCount: 1,
      partnershipYear: '2021',
      revenue: '6.2 triệu USD',
      specialties: ['Resort', 'Wellness tourism'],
      achievements: ['Luxury Resort', 'Hospitality Award'],
    },
    {
      id: 26,
      name: 'Đất Xanh Group',
      shortDescription: 'Chủ đầu tư đa ngành',
      description:
        'Phát triển các dự án bất động sản đa dạng từ nhà ở đến thương mại.',
      logoUrl: '/developer-partner/dat-xanh-group.webp',
      projectCount: 1,
      partnershipYear: '2017',
      revenue: '3.6 triệu USD',
      specialties: ['Residential', 'Riverside condo'],
      achievements: ['Versatile Developer', 'Market Growth'],
    },
  ],

  international: [
    {
      id: 1,
      name: 'Juwai IQI',
      shortDescription: 'Mạng lưới BĐS quốc tế',
      description:
        'Tập đoàn bất động sản quốc tế có mặt tại hơn 20 quốc gia, kết nối nhà đầu tư toàn cầu với thị trường Châu Á.',
      logoUrl: '/international-partner/juwai.png',
      countries: 20,
      agents: '40,000+',
      partnershipYear: '2015',
      specialties: [
        'Cross-border investment',
        'Global marketing',
        'International listings',
      ],
      achievements: [
        'Top Global Network',
        'Asia-Pacific Excellence',
        'Innovation in Outreach',
      ],
    },
    {
      id: 2,
      name: 'PropTech Asia',
      shortDescription: 'Nền tảng công nghệ BĐS',
      description:
        'Đơn vị tiên phong trong giải pháp công nghệ cho bất động sản tại Châu Á, tập trung vào số hóa và dữ liệu.',
      logoUrl: '/international-partner/asia-prop-tech.png',
      countries: 10,
      agents: '12,000+',
      partnershipYear: '2021',
      specialties: ['PropTech solutions', 'AI & analytics', 'Smart platforms'],
      achievements: [
        'Digital Transformation Award',
        'AI Adoption Leader',
        'PropTech Accelerator',
      ],
    },
    {
      id: 3,
      name: 'CBRE',
      shortDescription: 'Dịch vụ BĐS thương mại',
      description:
        'Tập đoàn dịch vụ bất động sản lớn nhất thế giới với hơn 100 quốc gia hoạt động.',
      logoUrl: '/international-partner/cbre.png',
      countries: 100,
      agents: '115,000+',
      partnershipYear: '2016',
      specialties: [
        'Commercial leasing',
        'Investment advisory',
        'Property management',
      ],
      achievements: [
        'Global Commercial Leader',
        'Top Investment Partner',
        'Real Estate Service Excellence',
      ],
    },
    {
      id: 4,
      name: 'Knight Frank',
      shortDescription: 'Tư vấn BĐS cao cấp',
      description:
        'Công ty tư vấn BĐS có trụ sở tại Anh, hoạt động tại hơn 60 quốc gia với hơn 125 năm kinh nghiệm.',
      logoUrl: '/international-partner/knight-frank.png',
      countries: 60,
      agents: '20,000+',
      partnershipYear: '2018',
      specialties: [
        'Luxury real estate',
        'Commercial properties',
        'Research & consultancy',
      ],
      achievements: [
        'Luxury Property Leader',
        'Top Market Advisor',
        'Global Partner Award',
      ],
    },
    {
      id: 5,
      name: 'Savills',
      shortDescription: 'Tư vấn & quản lý BĐS',
      description:
        'Một trong những công ty tư vấn BĐS hàng đầu thế giới có trụ sở tại Anh và mạng lưới toàn cầu.',
      logoUrl: '/international-partner/savills.png',
      countries: 70,
      agents: '39,000+',
      partnershipYear: '2019',
      specialties: [
        'Residential & commercial',
        'Valuation & advisory',
        'Global leasing',
      ],
      achievements: [
        'Service Excellence',
        'Trusted Advisor Award',
        'Global Reach Recognition',
      ],
    },
  ],

  bank: [
    {
      id: 1,
      name: 'Vietcombank',
      shortDescription: 'Ngân hàng TMCP Ngoại thương Việt Nam',
      description:
        'Một trong những ngân hàng lớn nhất Việt Nam, hỗ trợ gói vay mua nhà linh hoạt và bảo mật cao.',
      logoUrl: '/bank-partner/vietcombank.png',
      loanRate: '6.5%/năm',
      maxLoan: '85%',
      partnershipYear: '2017',
      benefits: ['Lãi suất ưu đãi', 'Thủ tục rõ ràng', 'Hỗ trợ 24/7'],
    },
    {
      id: 2,
      name: 'Techcombank',
      shortDescription: 'Ngân hàng TMCP Kỹ thương Việt Nam',
      description:
        'Tiên phong chuyển đổi số với hệ sinh thái vay mua nhà và thanh toán thông minh.',
      logoUrl: '/bank-partner/techcombank.png',
      loanRate: '6.8%/năm',
      maxLoan: '80%',
      partnershipYear: '2019',
      benefits: ['Vay online 100%', 'Xét duyệt nhanh', 'Không phí trả trước'],
    },
    {
      id: 3,
      name: 'MB Bank',
      shortDescription: 'Ngân hàng TMCP Quân đội',
      description:
        'Cung cấp các giải pháp tài chính linh hoạt, hỗ trợ vay mua nhà lãi suất cạnh tranh.',
      logoUrl: '/bank-partner/mbbank.png',
      loanRate: '6.9%/năm',
      maxLoan: '80%',
      partnershipYear: '2020',
      benefits: ['Ân hạn gốc 12 tháng', 'Tư vấn miễn phí', 'Giao dịch bảo mật'],
    },
    {
      id: 4,
      name: 'VPBank',
      shortDescription: 'Ngân hàng TMCP Việt Nam Thịnh Vượng',
      description:
        'Chuyên cung cấp sản phẩm vay tiêu dùng và vay thế chấp nhanh chóng, linh hoạt.',
      logoUrl: '/bank-partner/vpbank.png',
      loanRate: '7.2%/năm',
      maxLoan: '75%',
      partnershipYear: '2021',
      benefits: [
        'Xét duyệt nhanh',
        'Ưu đãi khách VIP',
        'Không cần chứng minh thu nhập',
      ],
    },
    {
      id: 5,
      name: 'BIDV',
      shortDescription: 'Ngân hàng TMCP Đầu tư và Phát triển Việt Nam',
      description:
        'Đơn vị tài chính uy tín lâu năm, cung cấp gói vay mua nhà lãi suất cố định dài hạn.',
      logoUrl: '/bank-partner/bidv.png',
      loanRate: '6.7%/năm',
      maxLoan: '80%',
      partnershipYear: '2018',
      benefits: ['Lãi suất ổn định', 'Vay đến 25 năm', 'Miễn phí định giá'],
    },
    {
      id: 6,
      name: 'ACB',
      shortDescription: 'Ngân hàng TMCP Á Châu',
      description:
        'Ngân hàng uy tín tại khu vực phía Nam với các sản phẩm vay thế chấp linh hoạt.',
      logoUrl: '/bank-partner/acb.png',
      loanRate: '7.0%/năm',
      maxLoan: '85%',
      partnershipYear: '2020',
      benefits: ['Duyệt hồ sơ trong ngày', 'Tỷ lệ vay cao', 'Chăm sóc tận tâm'],
    },
    {
      id: 7,
      name: 'Sacombank',
      shortDescription: 'Ngân hàng TMCP Sài Gòn Thương Tín',
      description:
        'Hỗ trợ gói vay mua nhà hấp dẫn và linh hoạt phù hợp với nhiều đối tượng khách hàng.',
      logoUrl: '/bank-partner/sacombank.png',
      loanRate: '6.9%/năm',
      maxLoan: '80%',
      partnershipYear: '2019',
      benefits: ['Miễn phí hồ sơ', 'Hạn mức cao', 'Giải ngân nhanh'],
    },
    {
      id: 8,
      name: 'VIB',
      shortDescription: 'Ngân hàng TMCP Quốc tế Việt Nam',
      description:
        'Ngân hàng dẫn đầu về trải nghiệm số, cung cấp các gói vay nhà đơn giản và minh bạch.',
      logoUrl: '/bank-partner/vib.png',
      loanRate: '7.1%/năm',
      maxLoan: '75%',
      partnershipYear: '2022',
      benefits: ['Ký hồ sơ online', 'Tư vấn 1:1', 'Ưu đãi phí dịch vụ'],
    },
  ],
};
