export const allProperties = {
  vietnam: [
    {
      id: 1,
      name: 'Vinhomes Grand Park',
      location: 'Quận 9, TP.HCM',
      city: 'hcmc',
      district: 'Quận 9',
      country: 'vietnam',
      type: 'Căn hộ cao cấp',
      status: 'active',
      price: 'Từ 3.2 tỷ',
      priceValue: 3200000000,
      bedrooms: 2,
      bathrooms: 2,
      area: 75,
      developer: 'Vingroup',
      completion: 'Q4/2024',
      views: 2341,
      inquiries: 45,
      leads: 12,
      sales: 8,
      images: ['/placeholder-2.webp?height=200&width=300'],
      features: [
        'Công viên 36ha',
        'Trường học liên cấp',
        'Bệnh viện',
        'Shopping mall',
      ],
      description: 'Dự án căn hộ cao cấp với không gian xanh rộng lớn...',
      createdAt: '2023-01-15',
      updatedAt: '2024-01-10',
      category: 'vietnam',
    },
    {
      id: 2,
      name: 'Vinhomes Smart City',
      location: 'Nam Từ Liêm, Hà Nội',
      city: 'hanoi',
      district: 'Nam Từ Liêm',
      country: 'vietnam',
      type: 'Căn hộ thông minh',
      status: 'active',
      price: 'Từ 2.8 tỷ',
      priceValue: 2800000000,
      bedrooms: 3,
      bathrooms: 2,
      area: 85,
      developer: 'Vingroup',
      completion: 'Q3/2024',
      views: 3241,
      inquiries: 67,
      leads: 18,
      sales: 11,
      images: ['/placeholder-2.webp?height=200&width=300'],
      features: ['Smart home', 'Công viên Nhật', 'Trường quốc tế', 'IoT'],
      description: 'Khu đô thị thông minh đầu tiên tại Hà Nội...',
      createdAt: '2023-03-10',
      updatedAt: '2024-01-05',
      category: 'vietnam',
    },
  ],
  international: [
    {
      id: 3,
      name: 'Marina Bay Residences',
      location: 'Marina Bay, Singapore',
      city: 'singapore',
      district: 'Marina Bay',
      country: 'singapore',
      type: 'Luxury Apartment',
      status: 'active',
      price: 'From $1.2M',
      priceValue: 1200000,
      bedrooms: 2,
      bathrooms: 2,
      area: 80,
      developer: 'CapitaLand',
      completion: 'Q2/2024',
      views: 3456,
      inquiries: 78,
      leads: 23,
      sales: 15,
      images: ['/placeholder-2.webp?height=200&width=300'],
      features: ['Marina view', 'Sky garden', 'Infinity pool', 'Concierge'],
      description: 'Luxury waterfront living in the heart of Singapore...',
      createdAt: '2023-02-20',
      updatedAt: '2024-01-08',
      category: 'international',
    },
    {
      id: 4,
      name: 'Pavilion Damansara Heights',
      location: 'Damansara Heights, KL',
      city: 'kualalumpur',
      district: 'Damansara Heights',
      country: 'malaysia',
      type: 'Luxury Condominium',
      status: 'draft',
      price: 'From RM 800K',
      priceValue: 800000,
      bedrooms: 3,
      bathrooms: 2,
      area: 100,
      developer: 'Malton Berhad',
      completion: 'Q1/2025',
      views: 1876,
      inquiries: 34,
      leads: 9,
      sales: 3,
      images: ['/placeholder-2.webp?height=200&width=300'],
      features: ['KLCC view', 'Sky lounge', 'Gym', 'Security'],
      description: 'Premium condominium in prestigious Damansara Heights...',
      createdAt: '2023-04-05',
      updatedAt: '2024-01-03',
      category: 'international',
    },
  ],
  resort: [
    {
      id: 5,
      name: 'Fusion Suites Danang Beach',
      location: 'Đà Nẵng, Việt Nam',
      city: 'danang',
      district: 'Ngũ Hành Sơn',
      country: 'vietnam',
      type: 'Condotel',
      status: 'active',
      price: 'Từ 8.5 tỷ',
      priceValue: 8500000000,
      bedrooms: 2,
      bathrooms: 2,
      area: 100,
      developer: 'Fusion Group',
      completion: 'Đã hoàn thành',
      views: 3240,
      inquiries: 89,
      leads: 34,
      sales: 18,
      images: ['/placeholder-2.webp?height=200&width=300'],
      features: ['Bãi biển riêng', 'Spa', 'Nhà hàng', 'Hồ bơi vô cực', 'Golf'],
      description: 'Resort cao cấp bên bờ biển Đà Nẵng...',
      createdAt: '2023-05-15',
      updatedAt: '2024-01-12',
      category: 'resort',
      rentalYield: '8-12%',
    },
    {
      id: 6,
      name: 'Movenpick Resort Waverly Phu Quoc',
      location: 'Phú Quốc, Việt Nam',
      city: 'phuquoc',
      district: 'Gành Dầu',
      country: 'vietnam',
      type: 'Villa',
      status: 'active',
      price: 'Từ 12 tỷ',
      priceValue: 12000000000,
      bedrooms: 3,
      bathrooms: 3,
      area: 120,
      developer: 'Movenpick',
      completion: 'Q3/2024',
      views: 2876,
      inquiries: 67,
      leads: 28,
      sales: 12,
      images: ['/placeholder-2.webp?height=200&width=300'],
      features: [
        'Bãi biển riêng',
        'Water park',
        'Kids club',
        'Multiple pools',
        'Diving center',
      ],
      description: 'Resort đảo nhiệt đới tại Phú Quốc...',
      createdAt: '2023-06-20',
      updatedAt: '2024-01-15',
      category: 'resort',
      rentalYield: '10-15%',
    },
  ],
};

export const getFilterOptions = (category: string) => {
  switch (category) {
    case 'vietnam':
      return {
        cities: [
          { value: 'hcmc', label: 'TP. Hồ Chí Minh' },
          { value: 'hanoi', label: 'Hà Nội' },
          { value: 'danang', label: 'Đà Nẵng' },
          { value: 'haiphong', label: 'Hải Phòng' },
        ],
        districts: [
          { value: 'quan-1', label: 'Quận 1', city: 'hcmc' },
          { value: 'quan-9', label: 'Quận 9', city: 'hcmc' },
          { value: 'ba-dinh', label: 'Ba Đình', city: 'hanoi' },
          { value: 'nam-tu-liem', label: 'Nam Từ Liêm', city: 'hanoi' },
        ],
        propertyTypes: [
          { value: 'can-ho', label: 'Căn hộ' },
          { value: 'villa', label: 'Villa' },
          { value: 'nha-pho', label: 'Nhà phố' },
          { value: 'dat-nen', label: 'Đất nền' },
        ],
      };
    case 'international':
      return {
        cities: [
          { value: 'singapore', label: 'Singapore' },
          { value: 'kualalumpur', label: 'Kuala Lumpur' },
          { value: 'bangkok', label: 'Bangkok' },
          { value: 'manila', label: 'Manila' },
        ],
        districts: [
          { value: 'marina-bay', label: 'Marina Bay', city: 'singapore' },
          { value: 'orchard', label: 'Orchard', city: 'singapore' },
          {
            value: 'damansara',
            label: 'Damansara Heights',
            city: 'kualalumpur',
          },
          { value: 'klcc', label: 'KLCC', city: 'kualalumpur' },
        ],
        propertyTypes: [
          { value: 'apartment', label: 'Apartment' },
          { value: 'condominium', label: 'Condominium' },
          { value: 'villa', label: 'Villa' },
          { value: 'townhouse', label: 'Townhouse' },
        ],
      };
    case 'resort':
      return {
        cities: [
          { value: 'danang', label: 'Đà Nẵng' },
          { value: 'phuquoc', label: 'Phú Quốc' },
          { value: 'nhatrang', label: 'Nha Trang' },
          { value: 'phanrang', label: 'Phan Rang' },
        ],
        districts: [
          { value: 'ngu-hanh-son', label: 'Ngũ Hành Sơn', city: 'danang' },
          { value: 'son-tra', label: 'Sơn Trà', city: 'danang' },
          { value: 'ganh-dau', label: 'Gành Dầu', city: 'phuquoc' },
          { value: 'duong-dong', label: 'Dương Đông', city: 'phuquoc' },
        ],
        propertyTypes: [
          { value: 'condotel', label: 'Condotel' },
          { value: 'villa', label: 'Villa' },
          { value: 'bungalow', label: 'Bungalow' },
          { value: 'suite', label: 'Suite' },
        ],
      };
    default:
      return { cities: [], districts: [], propertyTypes: [] };
  }
};

export const statusOptions = [
  { value: 'active', label: 'Đang hoạt động' },
  { value: 'draft', label: 'Bản nháp' },
  { value: 'archived', label: 'Đã lưu trữ' },
];

export const amenitiesList = [
  'Hồ bơi',
  'Gym',
  'Công viên',
  'Trường học',
  'Bệnh viện',
  'Shopping mall',
  'View sông',
  'Sky bar',
  'Spa',
  'Tennis',
  'Golf',
  'An ninh 24/7',
  'Bãi biển riêng',
  'Water park',
  'Kids club',
];
